version: "3.9"

services:
  backend:
    build:
      context: ./backend/GameLocalization
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  frontend:
    build:
      context: ./frontend/gamelocalization_frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
  postgres:
    image: postgres:latest
    container_name: gamelocalization_postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "gl_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 